   name: .NET

   on:
     push:
       branches: [ "main" ]
     pull_request:
       branches: [ "main" ]

   jobs:
     build:

       runs-on: ubuntu-latest

       steps:
       - uses: actions/checkout@v4
       - name: Setup .NET
         uses: actions/setup-dotnet@v4
         with:
           dotnet-version: 8.0.x
       - name: Install Aspire workload
         run: dotnet workload install aspire
       - name: Install required workloads
         run: dotnet workload restore
       - name: Restore dependencies
         run: dotnet restore
       - name: Format
         run: dotnet format --verify-no-changes --verbosity diagnostic
       - name: Build
         run: dotnet build --no-restore -p:TreatWarningsAsErrors=true
       - name: Test
         run: dotnet test --no-build --verbosity normal
